### ISSUE TITLE
how to do api call via postman

### ISSUE THREAD

**Issue by shanukagayashanc** [ellaisys/demo_cognito_app#2]

**Comment by amitdhongde** [comment]
@shanukagayashanc Thank you for reaching out. Do you need API routes? or payloads?

**Comment by shanukagayashanc** [comment]
Please share me swagger

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by shanuka** [comment]
sorry I was mistaken. I don't recall what issue :D

**Comment by amitdhongde** [comment]
![Untitled](https://github.com/ellaisys/demo_cognito_app/assets/24870900/f1230d60-3d99-45fc-91bd-a424ae2de38d)

Hope this helps !!
